grpc:
  # gRPC server ports
  grpcServerPort: "8080"
  # gRPC gateway port
  grpcGatewayPort: "8081"

prometheus:
  # Prometheus path
  prometheusPath: "/metrics"
  # Prometheus port
  prometheusPort: "9000"

swagger:
  swaggerEnabled: true
  # Swagger web port
  swaggerWebPort: "8082"
  # Swagger web path
  swaggerWebPath: "/sw/"
